name: "Tagged release with Gradle"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Distributions with Gradle Wrapper
        run: |
          cd 1.20.2-24w13a-fabric/
          ./gradlew build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: 1.20.2-24w13a-fabric/build/libs/*.jar